# Introducción a Pytorch

## Importamos y exploramos los "tensores"

In [4]:
!pip install matplotlib
!pip install numpy 
!pip install torch
!pip install torchvision

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 MB 1.7 MB/s eta 0:00:00m eta 0:00:010:00:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 40.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 36.5 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 39.2 MB/s eta 0:00:0031m48.6 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 35.1 MB/s eta 0:00:00


In [5]:
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7335, 0.5818, 0.0119],
        [0.7319, 0.5301, 0.0264],
        [0.3132, 0.8727, 0.9641],
        [0.5948, 0.8890, 0.2746],
        [0.2648, 0.1971, 0.8072]])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.9405, 1.5565, 0.3605],
        [0.7862, 0.9598, 0.8571],
        [1.0858, 1.1284, 1.6125],
        [1.3364, 1.6113, 0.7379],
        [0.6902, 0.2059, 1.6284]])


In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [12]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [13]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Descargamos los datos desde torchvision

In [15]:
import torchvision
import torchvision.transforms as transforms

In [16]:
transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,shuffle=True, num_workers=2)
testset = torchvision.datasets.CIFAR10(root='./data', train=False,download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,shuffle=False, num_workers=2)
classes = ('plane', 'car', 'bird', 'cat','deer', 'dog', 'frog', 'horse', 'ship', 'truck')

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
 
# Función para mostrar imagen
def imshow(img):
  img = img / 2 + 0.5 # desnormalizamos
  npimg = img.numpy()
  plt.imshow(np.transpose(npimg, (1, 2, 0)))
 
 
# obtenemos algunas imágenes de forma aleatoria
dataiter = iter(trainloader)
images, labels = dataiter.next_data()
 
# mostramos las imágenes
imshow(torchvision.utils.make_grid(images))
# imprimimos sus etiquetas
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))

## Creamos una red neuronal convolucional

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(3, 6, 5)
    self.pool = nn.MaxPool2d(2, 2)
    self.conv2 = nn.Conv2d(6, 16, 5)
    self.fc1 = nn.Linear(16 * 5 * 5, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
 
  def forward(self, x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16 * 5 * 5)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
 
 
net = Net()

## Definimos una función de pérdida y optimizador

In [ ]:
import torch.optim as optim
 
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

## Entrenamos la red

In [ ]:
for epoch in range(2): #recorremos el dataset varias veces
 
  running_loss = 0.0
  for i, data in enumerate(trainloader, 0):
    # obtenemos los inputs
    inputs, labels = data
 
    # ponemos en 0 los gradientes de los parámetros
    optimizer.zero_grad()
    
    # forward + backward + optimize
    outputs = net(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    
    # imprimimos resultados parciales
    running_loss += loss.item()
    if i % 2000 == 1999:
      print('[%d, %5d] pérdida: %.3f' % (epoch + 1, i + 1, running_loss / 2000))
      running_loss = 0.0
 
print('Entrenamiento finalizado')

## Hacemos la prueba con el test dataset

In [ ]:
dataiter = iter(testloader)
images, labels = dataiter.next()
 
# imprimimos las imágenes
imshow(torchvision.utils.make_grid(images))
print('Predicción: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))

## Revisamos el accuracy de nuestro modelo

In [ ]:
correct = 0
total = 0
with torch.no_grad():
  for data in testloader:
    images, labels = data
    outputs = net(images)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
 
print('Accuracy de la red en las 10000 imágenes de prueba: %d %%' % (
100 * correct / total))

## Revisamos el accuracy clase por clase

In [ ]:
class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))
with torch.no_grad():
  for data in testloader:
    images, labels = data
    outputs = net(images)
    _, predicted = torch.max(outputs, 1)
    c = (predicted == labels).squeeze()
    for i in range(4):
      label = labels[i]
      class_correct[label] += c[i].item()
      class_total[label] += 1
 
 
for i in range(10):
  print('Accuracy de %5s : %2d %%' % (
  classes[i], 100 * class_correct[i] / class_total[i]))