<a href="https://colab.research.google.com/github/majorquev/DBDC_202304_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [2]:
v <- c(a = 1, b=4,c = 5) # Recordar que podemos definir los elemntos de un vector con nombres
v

a b c 
1 4 5

In [4]:
#tip
letters
LETTERS

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
# Podemos guardar los objetos en slots con nombres


In [5]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = 10,
           letra = c("a","b"),
           pl = "hola soy una frase",
           mat = diag(1:3),
           lista = list(100, c(T,F)))

In [6]:
l1

$num
[1] 10

$letra
[1] "a" "b"

$pl
[1] "hola soy una frase"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$lista
$lista[[1]]
[1] 100

$lista[[2]]
[1]  TRUE FALSE

In [7]:
# estructura
str(l1)

List of 5
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE


In [8]:
length(l1)

[1] 5

In [12]:
# Podemos combinar listas
l2 <- list(prim = 1:2,
           seg = LETTERS)

str(l2)



List of 2
 $ prim: int [1:2] 1 2
 $ seg : chr [1:26] "A" "B" "C" "D" ...


In [14]:
# Combinamos las dos listas (l1,l2)
l3 <- c(l1,l2)
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [19]:
# Acceso mediante posición
# Queremos rescatar el elemtno de pos 4

l3[4]# Esto retorna un lista con el elemento

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [20]:
str(l3[4])

List of 1
 $ mat: int [1:3, 1:3] 1 0 0 0 2 0 0 0 3


In [21]:
l3[c(2,4)]# Retorna una lista con los elemtnos de pos 2  y 4

$letra
[1] "a" "b"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [23]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[1]# Esto es una lista
l3[[1]]# Esto es el objeto al interior de la lista


$num
[1] 10

[1] 10

In [24]:
#Ahora si
l3[[1]] + 5

[1] 15

In [25]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [27]:
# Del vector que está en la pos 7 de l3, quiero la décima letra.
l3[[7]][10]


[1] "J"

In [33]:
# De la lista que está en la pos 5, quiero el segundo elemento del vector de la segunda entrada
l3[5] # esta es la lista con la lista del slot 5


$lista
$lista[[1]]
[1] 100

$lista[[2]]
[1]  TRUE FALSE

In [34]:
l3[[5]]# esta es la lista guardada en el slot 5

[[1]]
[1] 100

[[2]]
[1]  TRUE FALSE

In [35]:
l3[[5]][[2]]# Es el vector que está en la segunda pos de la lista l3[[5]]

[1]  TRUE FALSE

In [40]:
l3[[5]][[2]][2]# Es segundo elmento del vector l3[[5]][[2]]

[1] FALSE

In [37]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [38]:
# Acceso mediante nombre

l3[["lista"]][[2]][2]

[1] FALSE

In [39]:
l3["mat"]# lista con la matriz


$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [41]:
l3[["mat"]]# Matriz

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [43]:
# acceso vía "$"
l3$mat# Es equivalente a l3[["mat"]]  o l3[[4]]




[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [45]:
l4 <- list(a = list(x = 1, y =2),
           b = list(w = 8, z = list(q = 10)))

In [46]:
str(l4)

List of 2
 $ a:List of 2
  ..$ x: num 1
  ..$ y: num 2
 $ b:List of 2
  ..$ w: num 8
  ..$ z:List of 1
  .. ..$ q: num 10


In [51]:
l4$b$z$q

#o equivalentemente.

l4[["b"]][["z"]][["q"]]

[1] 10

[1] 10

In [ ]:
# para saber el largo de la lista/vector

# Para obtener los nombres de la lista

# si quisiéramos renombrar los slots:


In [ ]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando


In [ ]:
# podemos modificar elementos dentro de un slot



### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [ ]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)



In [ ]:
# Acceso a columnas de un data.frame
## Igual que en una lista



In [ ]:
##  Ganamos acceso como matriz
# segundafila de df


# segunda columna y segunda fila




In [ ]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista


In [ ]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas


In [ ]:
# Referenciando las posiciones de las columnas


In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.
