<a href="https://colab.research.google.com/github/majorquev/DBDC_202304_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_01_matrices_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [2]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A

B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [3]:
# clase y atributo dim
class(A)

[1] "matrix" "array"

In [4]:
dim(A)

[1] 2 3

In [5]:
# Genere dos vectores del mismo largo y forme una matriz.

c1 <- 1:3
c2 <- 5:7



In [9]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

M1 <- cbind(c1,c2)
M2 <- rbind(c1,c2)
M1
M2

c1 c2
[1,] 1  5 
[2,] 2  6 
[3,] 3  7

[,1] [,2] [,3]
c1 1    2    3   
c2 5    6    7

In [14]:
colnames(M1)
rownames(M1)



[1] "c1" "c2"

NULL

In [15]:
rownames(M2)
colnames(M2)

[1] "c1" "c2"

NULL

In [16]:
# NOTA: Podemos añadir una fila a una matriz existente
f3 <- c(10,11,12)
rbind(M2,f3)

[,1] [,2] [,3]
c1  1    2    3  
c2  5    6    7  
f3 10   11   12

In [17]:
# NOTA: Podemos añadir una columna a una matriz existente
f3 <- c(10,11,12)
cbind(M1,f3)

c1 c2 f3
[1,] 1  5  10
[2,] 2  6  11
[3,] 3  7  12

In [18]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

rbind(M2,c(100,200))


Warning message in rbind(M2, c(100, 200)):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3]
c1   1    2    3 
c2   5    6    7 
   100  200  100

In [19]:
# función diag para la definición de matrices diagonales
#?diag 

diag(1:10)


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 1    0    0    0    0    0    0    0    0     0   
 [2,] 0    2    0    0    0    0    0    0    0     0   
 [3,] 0    0    3    0    0    0    0    0    0     0   
 [4,] 0    0    0    4    0    0    0    0    0     0   
 [5,] 0    0    0    0    5    0    0    0    0     0   
 [6,] 0    0    0    0    0    6    0    0    0     0   
 [7,] 0    0    0    0    0    0    7    0    0     0   
 [8,] 0    0    0    0    0    0    0    8    0     0   
 [9,] 0    0    0    0    0    0    0    0    9     0   
[10,] 0    0    0    0    0    0    0    0    0    10

In [21]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo: rescatar el elemnto de la segunda fila y tercera columna de M2
M2
M2[2,3]



[,1] [,2] [,3]
c1 1    2    3   
c2 5    6    7

c2 
 7

In [22]:
# quiero rescatar el elemento "(2,1)"

M2[2,1]

c2 
 5

In [23]:
# CUIDADO:No es lo mismo que 
M2[c(2,1)]# Acá R interpreta M2 como un vector (recorrido como columnas de la matriz) y retorna los elmentos de pos 2  y 1.

[1] 5 1

In [26]:
# Para acceder a una fila completa
M2
M2[2,]

# Para acceder a una columna completa

M2[,3]

[,1] [,2] [,3]
c1 1    2    3   
c2 5    6    7

[1] 5 6 7

c1 c2 
 3  7

In [27]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 6 (de la pos 2,2) por un -99 
M2[2,2] <- -99


In [28]:
M2

[,1] [,2] [,3]
c1 1      2  3   
c2 5    -99  7

In [32]:
# Acceso mediante nombres
# Primero pongamos nombres a las filas
rownames(M1) <- c("f1","f2","f3")

In [33]:
M1

c1 c2
f1 1  5 
f2 2  6 
f3 3  7

In [35]:
# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (3,2)

M1["f3","c2"]

[1] 7

In [40]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (3,2) de M3
# 1: Crear una matriz de 3x2 con TRUE en dichas posiciones y FALSE en las restantes.
ind <- matrix(c(T,F,F,F,F,T),nrow = 3, ncol=2)
ind


[,1]  [,2] 
[1,]  TRUE FALSE
[2,] FALSE FALSE
[3,] FALSE  TRUE

In [41]:
M1[ind]

[1] 1 7

In [42]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M1[M1 > 5]# Esto nos retorna los elementos de la matriz mayores a 5.

[1] 6 7

In [44]:
which(M1 > 5,arr.ind = TRUE)# Aprendimos algo nuevo! Gracias Néstor!

row col
f2 2   2  
f3 3   2

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [46]:
# transponer una matriz
M1
t(M1)

c1 c2
f1 1  5 
f2 2  6 
f3 3  7

f1 f2 f3
c1 1  2  3 
c2 5  6  7

In [47]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices
M1+M1


c1 c2
f1 2  10
f2 4  12
f3 6  14

In [49]:
# Multiplicación de matrices
M1 * M1 # multiplicación componente a componente

M1 %*% M2# multiplación matricial

c1 c2
f1 1  25
f2 4  36
f3 9  49

[,1] [,2] [,3]
f1 26   -493 38  
f2 32   -590 48  
f3 38   -687 58

In [50]:
# podemos calcular determinantes
# ?det
det(M1 %*% M2)


[1] 0

In [ ]:
# Podemos invertir matrices
# ?solve
