<a href="https://colab.research.google.com/github/majorquev/DBDC_202304_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [1]:
v <- c(a = 1, b=4,c = 5) # Recordar que podemos definir los elemntos de un vector con nombres
v

a b c 
1 4 5

In [3]:
#tip
letters
LETTERS

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
# Podemos guardar los objetos en slots con nombres


In [4]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = 10
,
           letra = c("a","b"),
           pl = "hola soy una frase",
           mat = diag(1:3),
           lista = list(100, c(T,F)))

In [5]:
l1

$num
[1] 10

$letra
[1] "a" "b"

$pl
[1] "hola soy una frase"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$lista
$lista[[1]]
[1] 100

$lista[[2]]
[1]  TRUE FALSE

In [6]:
# estructura
str(l1)

List of 5
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE


In [7]:
length(l1)

[1] 5

In [8]:
# Podemos combinar listas
l2 <- list(prim = 1:2,
           seg = LETTERS)

str(l2)



List of 2
 $ prim: int [1:2] 1 2
 $ seg : chr [1:26] "A" "B" "C" "D" ...


In [9]:
# Combinamos las dos listas (l1,l2)
l3 <- c(l1,l2)
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [10]:
# Acceso mediante posición
# Queremos rescatar el elemtno de pos 4

l3[4]# Esto retorna un lista con el elemento

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [11]:
str(l3[4])

List of 1
 $ mat: int [1:3, 1:3] 1 0 0 0 2 0 0 0 3


In [12]:
l3[c(2,4)]# Retorna una lista con los elemtnos de pos 2  y 4

$letra
[1] "a" "b"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [13]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[1]# Esto es una lista
l3[[1]]# Esto es el objeto al interior de la lista


$num
[1] 10

[1] 10

In [ ]:
#Ahora si
l3[[1]] + 5

[1] 15

In [ ]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [14]:
# Del vector que está en la pos 7 de l3, quiero la décima letra.
l3[[7]][10]


[1] "J"

In [15]:
# De la lista que está en la pos 5, quiero el segundo elemento del vector de la segunda entrada
l3[5] # esta es la lista con la lista del slot 5


$lista
$lista[[1]]
[1] 100

$lista[[2]]
[1]  TRUE FALSE

In [16]:
l3[[5]]# esta es la lista guardada en el slot 5

[[1]]
[1] 100

[[2]]
[1]  TRUE FALSE

In [17]:
l3[[5]][[2]]# Es el vector que está en la segunda pos de la lista l3[[5]]

[1]  TRUE FALSE

In [18]:
l3[[5]][[2]][2]# Es segundo elmento del vector l3[[5]][[2]]

[1] FALSE

In [19]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:2] "a" "b"
 $ pl   : chr "hola soy una frase"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ : num 100
  ..$ : logi [1:2] TRUE FALSE
 $ prim : int [1:2] 1 2
 $ seg  : chr [1:26] "A" "B" "C" "D" ...


In [20]:
# Acceso mediante nombre

l3[["lista"]][[2]][2]

[1] FALSE

In [21]:
l3["mat"]# lista con la matriz


$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [22]:
l3[["mat"]]# Matriz

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [ ]:
# acceso vía "$"
l3$mat# Es equivalente a l3[["mat"]]  o l3[[4]]




[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [46]:
l4 <- list(a = list(x = 1, y =2),
           b = list(w = 8, z = list(q = 10)),
           b = "X")

In [47]:
l4[which(names(l4) == "b")]

$b
$b$w
[1] 8

$b$z
$b$z$q
[1] 10



$b
[1] "X"

In [48]:
str(l4)

List of 3
 $ a:List of 2
  ..$ x: num 1
  ..$ y: num 2
 $ b:List of 2
  ..$ w: num 8
  ..$ z:List of 1
  .. ..$ q: num 10
 $ b: chr "X"


In [49]:
l4$b$z$q

#o equivalentemente.

l4[["b"]][["z"]][["q"]]

[1] 10

[1] 10

In [50]:
# para saber el largo de la lista/vector
length(l4)
# Para obtener los nombres de la lista
names(l4)
# si quisiéramos renombrar los slots. Ej. Cambiar el tercer nombre por "c".
names(l4)[3] <- "c"

[1] 3

[1] "a" "b" "b"

In [51]:
names(l4)

[1] "a" "b" "c"

In [52]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l4[["d"]] <- c(2:7)

In [53]:
# o alternativamente con "$"
l4$e <- LETTERS

In [54]:
str(l4)

List of 5
 $ a:List of 2
  ..$ x: num 1
  ..$ y: num 2
 $ b:List of 2
  ..$ w: num 8
  ..$ z:List of 1
  .. ..$ q: num 10
 $ c: chr "X"
 $ d: int [1:6] 2 3 4 5 6 7
 $ e: chr [1:26] "A" "B" "C" "D" ...


In [55]:
# podemos modificar elementos dentro de un slot
l4$c <- LETTERS


In [57]:
# Néstor quiere permutar entradas
l4 <- c(l4["a"],l4["c"],l4["b"],l4[4:length(l4)])

In [58]:
str(l4)

List of 5
 $ a:List of 2
  ..$ x: num 1
  ..$ y: num 2
 $ c: chr [1:26] "A" "B" "C" "D" ...
 $ b:List of 2
  ..$ w: num 8
  ..$ z:List of 1
  .. ..$ q: num 10
 $ d: int [1:6] 2 3 4 5 6 7
 $ e: chr [1:26] "A" "B" "C" "D" ...


In [59]:
#cambiar el contnido de a por e
aux <- l4$e

In [60]:
l4$e <- l4$a
l4$a <- aux 

In [61]:
str(l4)

List of 5
 $ a: chr [1:26] "A" "B" "C" "D" ...
 $ c: chr [1:26] "A" "B" "C" "D" ...
 $ b:List of 2
  ..$ w: num 8
  ..$ z:List of 1
  .. ..$ q: num 10
 $ d: int [1:6] 2 3 4 5 6 7
 $ e:List of 2
  ..$ x: num 1
  ..$ y: num 2


### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [63]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
df <- data.frame( edad = c(18,23,34,40),
                  nombre = c("miguel", "jorge", "angel", "ale"),
                  tiene_mascota = c(F,T,T,F)
                  )


In [64]:
str(df)

'data.frame':	4 obs. of  3 variables:
 $ edad         : num  18 23 34 40
 $ nombre       : chr  "miguel" "jorge" "angel" "ale"
 $ tiene_mascota: logi  FALSE TRUE TRUE FALSE


In [65]:
df

edad nombre tiene_mascota
1 18   miguel FALSE        
2 23   jorge   TRUE        
3 34   angel   TRUE        
4 40   ale    FALSE

In [67]:
# Acceso a columnas de un data.frame (Ej acceder a la columna nombre)
## Como en una matriz
df[,2]# retorna un vector con los elementos de la columna.
df[,"nombre"]




[1] "miguel" "jorge"  "angel"  "ale"

[1] "miguel" "jorge"  "angel"  "ale"

In [69]:
## Igual que en una lista
df$nombre# retorna un vector con los elementos de la columna.
df[[2]]
df[["nombre"]]

[1] "miguel" "jorge"  "angel"  "ale"

[1] "miguel" "jorge"  "angel"  "ale"

[1] "miguel" "jorge"  "angel"  "ale"

In [70]:
## Igual que en una lista
df[2]
df["nombre"]

nombre
1 miguel
2 jorge 
3 angel 
4 ale

nombre
1 miguel
2 jorge 
3 angel 
4 ale

In [72]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila
df[2,2]



edad nombre tiene_mascota
2 23   jorge  TRUE

[1] "jorge"

In [73]:
df[2,"nombre"]

[1] "jorge"

**NOTA**: Nombres de columnas y filas.
Idem que para el caso de matrices


In [76]:
names(df)#Por defecto apunta a los nombres de las columnas
colnames(df)
rownames(df)# Por defecto retorna el numero de fila


[1] "edad"          "nombre"        "tiene_mascota"

[1] "edad"          "nombre"        "tiene_mascota"

[1] "1" "2" "3" "4"

In [81]:
#número de filas
N <- nrow(df)

In [79]:
dim(df)[1]

[1] 4

In [82]:
1:N

[1] 1 2 3 4

In [83]:
paste("f", 1:N,  sep = "_")

[1] "f_1" "f_2" "f_3" "f_4"

In [84]:
rownames(df) <- paste("f", 1:N,  sep = "_")

In [85]:
df

edad nombre tiene_mascota
f_1 18   miguel FALSE        
f_2 23   jorge   TRUE        
f_3 34   angel   TRUE        
f_4 40   ale    FALSE

In [89]:
#Podemos acceder aun fila a través del nombre:
df["f_2","nombre"]

[1] "jorge"

In [92]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$rut <- c("1-2","1-5","2-k", "10-0")
df[["genero"]] <- c("M","M","M","F")

In [93]:
df

edad nombre tiene_mascota rut  genero
f_1 18   miguel FALSE         1-2  M     
f_2 23   jorge   TRUE         1-5  M     
f_3 34   angel   TRUE         2-k  M     
f_4 40   ale    FALSE         10-0 F

In [97]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3
df[,c(1,3)]# Si pensamos como matriz
df[c(1,3)]# Si pensamos como lista
# Referenciando el nombre de las columnas
df[,c("edad","tiene_mascota")]# Si pensamos como matriz
df[c("edad","tiene_mascota")]# Si pensamos como lista

edad tiene_mascota
f_1 18   FALSE        
f_2 23    TRUE        
f_3 34    TRUE        
f_4 40   FALSE

edad tiene_mascota
f_1 18   FALSE        
f_2 23    TRUE        
f_3 34    TRUE        
f_4 40   FALSE

edad tiene_mascota
f_1 18   FALSE        
f_2 23    TRUE        
f_3 34    TRUE        
f_4 40   FALSE

edad tiene_mascota
f_1 18   FALSE        
f_2 23    TRUE        
f_3 34    TRUE        
f_4 40   FALSE

In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.


# Agregar filas a un Dataframe

In [120]:
#fila nueva
f_nueva <- data.frame(edad = 27,
                      nombre = "isa",
                      tiene_mascota = T,
                      rut = "6-7", 
                      genero = "F")

In [121]:
f_nueva

edad nombre tiene_mascota rut genero
1 27   isa    TRUE          6-7 F

In [123]:
df <- rbind(df, f_nueva)# Esta función aliza la unión por los nombres de las columnas.

In [124]:
df

edad nombre tiene_mascota rut  genero
f_1 18   miguel FALSE         1-2  M     
f_2 23   jorge   TRUE         1-5  M     
f_3 34   angel   TRUE         2-k  M     
f_4 40   ale    FALSE         10-0 F     
1   27   isa     TRUE         6-7  F

In [ ]:
#dplyr::bind_rows() , esta es una opción más robusta.

#NOTA:
Si utilizamos todo lo aprendido, estamos en condiciones de realizar consultas más complejas a nuestra tablas.

In [125]:
df

edad nombre tiene_mascota rut  genero
f_1 18   miguel FALSE         1-2  M     
f_2 23   jorge   TRUE         1-5  M     
f_3 34   angel   TRUE         2-k  M     
f_4 40   ale    FALSE         10-0 F     
1   27   isa     TRUE         6-7  F

In [128]:
# Quiero identificar las personas con mascotas y cuya edad sea mayor a 25 años.
df[(df$tiene_mascota == TRUE) & (df$edad > 25),]

edad nombre tiene_mascota rut genero
f_3 34   angel  TRUE          2-k M     
1   27   isa    TRUE          6-7 F

In [ ]:
#Si queremos solo el rut y el nombre

In [129]:
df[(df$tiene_mascota == TRUE) & (df$edad > 25),c("nombre","rut")]

nombre rut
f_3 angel  2-k
1   isa    6-7